/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as InsightsIndexRouteImport } from './routes/insights/index'
import { Route as InsightsSlugRouteImport } from './routes/insights/$slug'
import { Route as InsightsInflationPortfolioRouteImport } from './routes/insights/inflation-portfolio'
import { Route as InsightsKenoSomriddhiteBiniyogRouteImport } from './routes/insights/keno-somriddhite-biniyog'
import { Route as InsightsKrishiKhateBiniyogRouteImport } from './routes/insights/krishi-khate-biniyog'
import { Route as InsightsSmeHalalBiniyogRouteImport } from './routes/insights/sme-halal-biniyog'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as ApiPublicRevealDetailsRouteImport } from './routes/api/public/reveal-details'
import { Route as AdminDashboardBlogNewRouteImport } from './routes/admin/dashboard_.blog.new'
import { Route as AdminDashboardBlogPostIdEditRouteImport } from './routes/admin/dashboard_.blog.$postId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsInflationPortfolioRoute =
  InsightsInflationPortfolioRouteImport.update({
    id: '/inflation-portfolio',
    path: '/inflation-portfolio',
    getParentRoute: () => InsightsRoute,
  } as any)
const InsightsKenoSomriddhiteBiniyogRoute =
  InsightsKenoSomriddhiteBiniyogRouteImport.update({
    id: '/keno-somriddhite-biniyog',
    path: '/keno-somriddhite-biniyog',
    getParentRoute: () => InsightsRoute,
  } as any)
const InsightsKrishiKhateBiniyogRoute =
  InsightsKrishiKhateBiniyogRouteImport.update({
    id: '/krishi-khate-biniyog',
    path: '/krishi-khate-biniyog',
    getParentRoute: () => InsightsRoute,
  } as any)
const InsightsSmeHalalBiniyogRoute = InsightsSmeHalalBiniyogRouteImport.update({
  id: '/sme-halal-biniyog',
  path: '/sme-halal-biniyog',
  getParentRoute: () => InsightsRoute,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRevealDetailsRoute = ApiPublicRevealDetailsRouteImport.update({
  id: '/api/public/reveal-details',
  path: '/api/public/reveal-details',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardBlogNewRoute = AdminDashboardBlogNewRouteImport.update({
  id: '/admin/dashboard_/blog/new',
  path: '/admin/dashboard/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardBlogPostIdEditRoute =
  AdminDashboardBlogPostIdEditRouteImport.update({
    id: '/admin/dashboard_/blog/$postId/edit',
    path: '/admin/dashboard/blog/$postId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/inflation-portfolio': typeof InsightsInflationPortfolioRoute
  '/insights/keno-somriddhite-biniyog': typeof InsightsKenoSomriddhiteBiniyogRoute
  '/insights/krishi-khate-biniyog': typeof InsightsKrishiKhateBiniyogRoute
  '/insights/sme-halal-biniyog': typeof InsightsSmeHalalBiniyogRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/api/public/reveal-details': typeof ApiPublicRevealDetailsRoute
  '/admin/dashboard/blog/new': typeof AdminDashboardBlogNewRoute
  '/admin/dashboard/blog/$postId/edit': typeof AdminDashboardBlogPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/reviews': typeof ReviewsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/inflation-portfolio': typeof InsightsInflationPortfolioRoute
  '/insights/keno-somriddhite-biniyog': typeof InsightsKenoSomriddhiteBiniyogRoute
  '/insights/krishi-khate-biniyog': typeof InsightsKrishiKhateBiniyogRoute
  '/insights/sme-halal-biniyog': typeof InsightsSmeHalalBiniyogRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/admin': typeof AdminIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/api/public/reveal-details': typeof ApiPublicRevealDetailsRoute
  '/admin/dashboard/blog/new': typeof AdminDashboardBlogNewRoute
  '/admin/dashboard/blog/$postId/edit': typeof AdminDashboardBlogPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/inflation-portfolio': typeof InsightsInflationPortfolioRoute
  '/insights/keno-somriddhite-biniyog': typeof InsightsKenoSomriddhiteBiniyogRoute
  '/insights/krishi-khate-biniyog': typeof InsightsKrishiKhateBiniyogRoute
  '/insights/sme-halal-biniyog': typeof InsightsSmeHalalBiniyogRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/api/public/reveal-details': typeof ApiPublicRevealDetailsRoute
  '/admin/dashboard_/blog/new': typeof AdminDashboardBlogNewRoute
  '/admin/dashboard_/blog/$postId/edit': typeof AdminDashboardBlogPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/insights'
    | '/reviews'
    | '/admin/dashboard'
    | '/admin/login'
    | '/insights/$slug'
    | '/insights/inflation-portfolio'
    | '/insights/keno-somriddhite-biniyog'
    | '/insights/krishi-khate-biniyog'
    | '/insights/sme-halal-biniyog'
    | '/opportunities/$id'
    | '/admin/'
    | '/insights/'
    | '/opportunities/'
    | '/api/public/reveal-details'
    | '/admin/dashboard/blog/new'
    | '/admin/dashboard/blog/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/reviews'
    | '/admin/dashboard'
    | '/admin/login'
    | '/insights/$slug'
    | '/insights/inflation-portfolio'
    | '/insights/keno-somriddhite-biniyog'
    | '/insights/krishi-khate-biniyog'
    | '/insights/sme-halal-biniyog'
    | '/opportunities/$id'
    | '/admin'
    | '/insights'
    | '/opportunities'
    | '/api/public/reveal-details'
    | '/admin/dashboard/blog/new'
    | '/admin/dashboard/blog/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/insights'
    | '/reviews'
    | '/admin/dashboard'
    | '/admin/login'
    | '/insights/$slug'
    | '/insights/inflation-portfolio'
    | '/insights/keno-somriddhite-biniyog'
    | '/insights/krishi-khate-biniyog'
    | '/insights/sme-halal-biniyog'
    | '/opportunities/$id'
    | '/admin/'
    | '/insights/'
    | '/opportunities/'
    | '/api/public/reveal-details'
    | '/admin/dashboard_/blog/new'
    | '/admin/dashboard_/blog/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ApiPublicRevealDetailsRoute: typeof ApiPublicRevealDetailsRoute
  AdminDashboardBlogNewRoute: typeof AdminDashboardBlogNewRoute
  AdminDashboardBlogPostIdEditRoute: typeof AdminDashboardBlogPostIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/inflation-portfolio': {
      id: '/insights/inflation-portfolio'
      path: '/inflation-portfolio'
      fullPath: '/insights/inflation-portfolio'
      preLoaderRoute: typeof InsightsInflationPortfolioRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/keno-somriddhite-biniyog': {
      id: '/insights/keno-somriddhite-biniyog'
      path: '/keno-somriddhite-biniyog'
      fullPath: '/insights/keno-somriddhite-biniyog'
      preLoaderRoute: typeof InsightsKenoSomriddhiteBiniyogRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/krishi-khate-biniyog': {
      id: '/insights/krishi-khate-biniyog'
      path: '/krishi-khate-biniyog'
      fullPath: '/insights/krishi-khate-biniyog'
      preLoaderRoute: typeof InsightsKrishiKhateBiniyogRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/sme-halal-biniyog': {
      id: '/insights/sme-halal-biniyog'
      path: '/sme-halal-biniyog'
      fullPath: '/insights/sme-halal-biniyog'
      preLoaderRoute: typeof InsightsSmeHalalBiniyogRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reveal-details': {
      id: '/api/public/reveal-details'
      path: '/api/public/reveal-details'
      fullPath: '/api/public/reveal-details'
      preLoaderRoute: typeof ApiPublicRevealDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard_/blog/new': {
      id: '/admin/dashboard_/blog/new'
      path: '/admin/dashboard/blog/new'
      fullPath: '/admin/dashboard/blog/new'
      preLoaderRoute: typeof AdminDashboardBlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard_/blog/$postId/edit': {
      id: '/admin/dashboard_/blog/$postId/edit'
      path: '/admin/dashboard/blog/$postId/edit'
      fullPath: '/admin/dashboard/blog/$postId/edit'
      preLoaderRoute: typeof AdminDashboardBlogPostIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsInflationPortfolioRoute: typeof InsightsInflationPortfolioRoute
  InsightsKenoSomriddhiteBiniyogRoute: typeof InsightsKenoSomriddhiteBiniyogRoute
  InsightsKrishiKhateBiniyogRoute: typeof InsightsKrishiKhateBiniyogRoute
  InsightsSmeHalalBiniyogRoute: typeof InsightsSmeHalalBiniyogRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsInflationPortfolioRoute: InsightsInflationPortfolioRoute,
  InsightsKenoSomriddhiteBiniyogRoute: InsightsKenoSomriddhiteBiniyogRoute,
  InsightsKrishiKhateBiniyogRoute: InsightsKrishiKhateBiniyogRoute,
  InsightsSmeHalalBiniyogRoute: InsightsSmeHalalBiniyogRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ApiPublicRevealDetailsRoute: ApiPublicRevealDetailsRoute,
  AdminDashboardBlogNewRoute: AdminDashboardBlogNewRoute,
  AdminDashboardBlogPostIdEditRoute: AdminDashboardBlogPostIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
